### ISSUE TITLE
Gentoo/Archlinux is being recognized as Debian

### ISSUE THREAD

**Issue by Astranox** [keenerd/pacgraph#3]
The script is looking for the file "apt" to recognize a Debian OS
(At least) on Gentoo /usr/bin/apt belongs to the package "java-config"
"apt-get" probably is the better pattern.

Necessary changes in file "pacgraph":
-    if any(map(exists, 'dpkg apt aptitude'.split())):
-    if any(map(exists, 'dpkg apt-get aptitude'.split())):

**Comment by keenerd** [comment]
Should be fixed now.
